export CRI_CONTAINERD="yes"
export CRI_RUNTIME="containerd"
export KATA_HYPERVISOR="qemu"
export KATA_BUILD_CC="yes"
export TEE_TYPE="tdx"
export TEE_CONFIDENTIAL_GUEST="false"
export KATA_BUILD_KERNEL_TYPE="tdx"
export KATA_BUILD_QEMU_TYPE="tdx"
export KUBERNETES="yes"

export USE_DOCKER="true"
export CRIO="false"
export CRI_CONTAINERD="true"
export CRI_RUNTIME="containerd"
#export CI_JOB="CRI_CONTAINERD_K8S_MINIMAL"
export CCV0="yes"
export CI_JOB="METRICS"
